# Import modules
from neuroevolution.environments.base_environment import BaseEnvironment
from neuroevolution.environments.other.xor_environment import XOREnvironment
from neuroevolution.environments.other.xor_environment import XORWeightTrainingEnvironment
