# Import modules
from neuroevolution.encodings.direct.direct_encoding_model import DirectEncodingModel
from neuroevolution.encodings.direct.direct_encoding_genome import DirectEncodingGenome, DirectEncodingGene
