# Import modules
from tfne.encodings.codeepneat.modules.codeepneat_module_association import MODULES
from tfne.encodings.codeepneat.modules.codeepneat_module_base import CoDeepNEATModuleBase
from tfne.encodings.codeepneat.modules.codeepneat_module_conv2dmaxpool2ddropout import \
    CoDeepNEATModuleConv2DMaxPool2DDropout
from tfne.encodings.codeepneat.modules.codeepneat_module_densedropout import CoDeepNEATModuleDenseDropout
